import{a as L,S as v,i as c}from"./assets/vendor-DEenWwFD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const n of i.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&e(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function e(t){if(t.ep)return;t.ep=!0;const i=s(t);fetch(t.href,i)}})();function g(o){return o.map(({webformatURL:r,largeImageURL:s,tags:e,likes:t,views:i,comments:n,downloads:w})=>`
                <li class="gallery-item">
                    <a href="${s}"><img src="${r}" alt="${e}" width="360" height="152"/>
                        <ul class="image-descr-list">
                            <li class="image-descr-item">Likes: ${t}</li>
                            <li class="image-descr-item">Views: ${i}</li>
                            <li class="image-descr-item">Comments: ${n}</li>
                            <li class="image-descr-item">Downloads: ${w}</li>
                        </ul>
                    </a>
                </li>
                `).join("")}async function p(o,r,s){const{data:e}=await L.get(`${o}?key=${r}&${s}`);return console.log("await data",e),e}const f=new v(".gallery-item a",{captionDelay:250,captions:!0,captionsData:"alt"});let h=1;const y="47534106-2225be5d16534437522f359a0",d=new URLSearchParams({key:y,q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:15}),b="https://pixabay.com/api/";let a=document.querySelector(".js-load-more");a.classList.replace("load-more","load-more-hidden");const l=document.querySelector(".loader");l.style.visibility="hidden";const m=document.querySelector(".gallery"),u=document.querySelector(".js-search-form");u.addEventListener("submit",function(o){o.preventDefault(),m.innerHTML="",l.style.visibility="visible",a.classList.replace("load-more","load-more-hidden");const s=o.target.querySelector(".search-input").value.trim();if(console.log("input-trim:",s),!s){c.show({messageColor:"white",backgroundColor:"red",position:"topRight",close:!0,title:"",message:"Please, enter text"}),l.style.visibility="hidden",u.reset();return}d.set("q",s),d.set("page",1),p(b,y,d).then(e=>{e.hits.length===0?c.show({messageColor:"white",backgroundColor:"red",position:"topRight",close:!0,title:"",message:"Sorry, there are no images matching your search query. Please try again!"}):e.hits.length===e.total?m.insertAdjacentHTML("beforeend",g(e.hits)):e.hits.length<e.total&&(m.insertAdjacentHTML("beforeend",g(e.hits)),a.classList.replace("load-more-hidden","load-more")),f.refresh(),l.style.visibility="hidden"}).catch(e=>c.show({messageColor:"white",backgroundColor:"red",position:"topRight",close:!0,title:`${e}`,message:"Sorry, there are no images matching your search query. Please try again!"}),l.style.visibility="hidden").finally(()=>u.reset())});a.addEventListener("click",function(){a.disable=!0,h++,d.set("page",h),l.style.visibility="visible",p(b,y,d).then(o=>{const r=o.total/h;l.style.visibility="hidden",m.insertAdjacentHTML("beforeend",g(o.hits)),f.refresh();const e=document.querySelector(".gallery-item").getBoundingClientRect().height;console.log(e),window.scrollBy({left:0,top:400,behavior:"smooth"}),r<=15&&(a.classList.replace("load-more","load-more-hidden"),c.show({messageColor:"white",backgroundColor:"red",position:"bottomCenter",close:!0,title:"",message:"Sorry, there are no more images! Please try other query!"}),l.style.visibility="hidden",h=1)}).catch(o=>c.show({messageColor:"white",backgroundColor:"red",position:"topRight",close:!0,title:`${o}`,message:"Sorry, there are no images matching your search query. Please try again!"}),l.style.visibility="hidden").finally(()=>a.disable=!1)});
//# sourceMappingURL=index.js.map
