import{a as L,S as C,i as n}from"./assets/vendor-DEenWwFD.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&e(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function e(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();function h(r){return r.map(({webformatURL:i,largeImageURL:s,tags:e,likes:t,views:o,comments:l,downloads:w})=>`
                <li class="gallery-item">
                    <a href="${s}"><img src="${i}" alt="${e}" width="360" height="152"/>
                        <ul class="image-descr-list">
                            <li class="image-descr-item">Likes: ${t}</li>
                            <li class="image-descr-item">Views: ${o}</li>
                            <li class="image-descr-item">Comments: ${l}</li>
                            <li class="image-descr-item">Downloads: ${w}</li>
                        </ul>
                    </a>
                </li>
                `).join("")}async function f(r,i,s){const{data:e}=await L.get(`${r}?key=${i}&${s}`);return console.log("await data",e),e}const y=new C(".gallery-item a",{captionDelay:250,captions:!0,captionsData:"alt"});let m=1;const p="47534106-2225be5d16534437522f359a0",d=new URLSearchParams({key:p,q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:15}),b="https://pixabay.com/api/";let a=document.querySelector(".js-load-more");a.classList.replace("load-more","load-more-hidden");const g=document.querySelector(".loader");g.style.visibility="hidden";const c=document.querySelector(".gallery"),u=document.querySelector(".js-search-form");u.addEventListener("submit",function(r){r.preventDefault(),c.innerHTML="",g.style.visibility="visible",a.classList.replace("load-more","load-more-hidden");const s=r.target.querySelector(".search-input").value.trim();if(console.log("input-trim:",s),!s){n.show({messageColor:"white",backgroundColor:"red",position:"topRight",close:!0,title:"",message:"Please, enter text"}),u.reset();return}d.set("q",s),f(b,p,d).then(e=>{e.hits.length===0?n.show({messageColor:"white",backgroundColor:"red",position:"topRight",close:!0,title:"",message:"Sorry, there are no images matching your search query. Please try again!"}):e.hits.length===e.total?c.insertAdjacentHTML("beforeend",h(e.hits)):e.hits.length<e.total&&(c.insertAdjacentHTML("beforeend",h(e.hits)),a.classList.replace("load-more-hidden","load-more")),y.refresh(),g.style.visibility="hidden"}).catch(e=>n.show({messageColor:"white",backgroundColor:"red",position:"topRight",close:!0,title:`${e}`,message:"Sorry, there are no images matching your search query. Please try again!"})).finally(()=>u.reset())});a.addEventListener("click",function(){a.disable=!0,m++,d.set("page",m),f(b,p,d).then(r=>{const i=r.total/m;c.insertAdjacentHTML("beforeend",h(r.hits)),y.refresh();const e=document.querySelector(".gallery-item").getBoundingClientRect().height;console.log(e),window.scrollBy({left:0,top:400,behavior:"smooth"}),i<=15&&(a.classList.replace("load-more","load-more-hidden"),n.show({messageColor:"white",backgroundColor:"red",position:"bottomCenter",close:!0,title:"",message:"Sorry, there are no more images! Please try other query!"}))}).catch(r=>n.show({messageColor:"white",backgroundColor:"red",position:"topRight",close:!0,title:`${r}`,message:"Sorry, there are no images matching your search query. Please try again!"})).finally(()=>a.disable=!1)});
//# sourceMappingURL=index.js.map
